### ISSUE TITLE
Adding `datetime.date` Support

### ISSUE THREAD

**Issue by zacharylawrence** [vega/altair#2199]
I looked around for an existing issue, but didn't see one. Please let me know if I should respond somewhere else instead!

Currently, putting a datetime.date in an altair chart gives the error:
```
TypeError: Object of type date is not JSON serializable
```

Are there ideas to support datetime.date in the future?

For example:
```python
data = pd.DataFrame({
    "time": [datetime.date(2020, 5, 1), datetime.date(2020, 5, 3)],
    "value": [3, 5],
})

alt.Chart(data).mark_line().encode(
    x="time",
    y="value",
)
```

**Comment by jakevdp** [comment]
The way to support that would be to update `sanitize_dataframe` to convert these into proper timestamps: https://github.com/altair-viz/altair/blob/03f37ca8b2701bf8d9e61646cacf8eee2edcad87/altair/utils/core.py#L243

It hasn't been done yet because it hasn't come up very often: generally timestamps in dataframes come in datetime-typed columns, rather than object-typed columns containing Python dates.

**Comment by zacharylawrence** [comment]
Thanks for the clear explanation! Would you be open to a PR to this effect?

To add some background, this has come up from reading a parquet file with DATE type column: https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#date

**Comment by jakevdp** [comment]
Sure, a PR would be great!
