### ISSUE TITLE
Adding a jitter function

### ISSUE THREAD

**Issue by cmbfuqua** [vega/altair#2500]
As I have been using Altair in work and school, one thing that I've had to do by hand is add some 'noise' or a jitter to the data to help show distribution of the data. It would be nice to add this as a scale argument so you can specify which axis you want the jitter to be on ex. 
alair.Chart(data).mark_point().encode(
     altair.X('column1',scale = altair.Scale(jitter = True)), # This one adds jitter left to right
     altair.Y('column2',scale = altair.Scale(jitter = True))  # This one adds jitter top to bottom
)

This is something I think would help bring the altair visualizations to the next level. 
If there is something like this already in the package please let me know, but I haven't been able to find something like this through a built in function.

**Comment by jakevdp** [comment]
There is an example of adding jitter at https://altair-viz.github.io/gallery/stripplot.html

Because the arguments to `alt.Scale` reflect the keys supported by the Vega-Lite schema, adding arguments like this is not a decision we can make from the Altair package itself, but rather would require an enhancement to Vega-Lite.

**Comment by cmbfuqua** [comment]
Thank you!
