### ISSUE TITLE
Include gallery example of point paths on hover from Vega gallery

### ISSUE THREAD

**Issue by joelostblom** [vega/altair#2980]
I was reviewing the vega examples and think [this one is pretty cool](https://vega.github.io/vega/examples/global-development/) and could be useful to include in the Altair gallery as well, possibly with a search box as mentioned in https://github.com/altair-viz/altair/issues/2760#issuecomment-1477186125

**Comment by dsmedia** [comment]
I've posted a [question](https://stackoverflow.com/questions/78686169/implementing-dimpvis-like-time-based-interaction-in-vega-lite) on Stack Overflow about how this kind of interaction might be implemented in Vega-Lite.

It wasn't immediately clear to me what capabilities Altair might have for this kind of interaction, which I agree is very cool. I figured that understanding the possibilities and limitations in Vega-Lite would be a good first step to determine potential Altair implementations, whether partial or complete.

**Comment by dsmedia** [comment]
I've made progress on porting the Gapminder visualization [example](https://vega.github.io/vega/examples/global-development/) from Vega to Altair, focusing on the hover path and adding a search box. I'd like to share my current implementation and discuss the remaining issues.

### Progress Made
- Implemented a slider for selecting the year
- Added a search box for filtering countries
- Implemented filtering based on both conditions
- Created hover effects for displaying country trajectories and a single country name
- Added a large background year label based on the slider selection

### Remaining Issues
- Hover behavior on invisible points: Currently, hovering over invisible points (i.e., points not selected by the year slider or search box) still results in labels and lines appearing. This is probably not desired.
- Color encoding: The current implementation encodes color by country, not by region as specified in the original Vega example. This makes it harder to discern regional patterns in the data. My attempt to encode color by region ended up distorting the lines on hover.
- There are likely more direct or efficient ways to implement this than the approach I took.

### Next Steps

- Address the hover behavior issue to ensure that only visible points respond to hover events.
- Modify the color encoding to use regions instead of countries, while maintaining the ability to highlight individual country trajectories.
- Add legend back once regional color encoding is fixed.

### Current Implementation
Here's the code for the current state of the visualization:
```python

import altair as alt
from vega_datasets import data

# Data source
source = data.gapminder.url

# X-value slider
x_slider = alt.binding_range(min=1955, max=2005, step=5, name='Year: ')
x_select = alt.selection_point(name="x_select", fields=['year'], bind=x_slider, value=1980)

# Search box for country name
search_box = alt.param(
    value='',
    bind=alt.binding(input='search', placeholder="Country", name='Search ')
)

# Base chart
base = alt.Chart(source).encode(
    x=alt.X('fertility:Q', scale=alt.Scale(zero=False), title='Fertility'),
    y=alt.Y('life_expect:Q', scale=alt.Scale(zero=False), title='Life Expectancy'),
    color=alt.Color('country:N', legend=None)
)

# Points that are always visible (filtered by slider and search)
visible_points = base.mark_circle(size=100).encode(
    opacity=alt.condition(x_select | search_box, alt.value(1), alt.value(0))
).add_params(x_select).transform_filter(
    x_select
).transform_filter(
    alt.expr.test(alt.expr.regexp(search_box, 'i'), alt.datum.country)
)

# Hover selection
hover = alt.selection_point(on='mouseover', fields=['country'], empty=False)

# Line that appears on hover
hover_line = base.mark_line(point=True).encode(
    opacity=alt.condition(hover, alt.value(0.3), alt.value(0))
).add_params(hover)

# Year labels
year_labels = base.mark_text(align='left', dx=5, dy=-5).encode(
    text='year:O'
).transform_filter(hover)

# Country labels
country_labels = base.mark_text(align='left', dx=5, dy=-25, fontSize=24).encode(
    text='country:N'
).transform_filter(hover).transform_filter(x_select)

background_year = alt.Chart(source).mark_text(
    align='center',
    baseline='middle',
    fontSize=96,
    opacity=0.2,
    x='width',
    y='height',
    dx=-400,  
    dy=-300   
).encode(
    text='year:O'
).transform_filter(
    x_select
).transform_aggregate(
    year='max(year)'  # This ensures we only get one label
)

# Combine all layers
chart = alt.layer(
    visible_points, year_labels, country_labels, hover_line, background_year
).properties(
    width=800,
    height=600,
    padding=50  # Padding required to ensure country labels fit
).configure_axis(
    labelFontSize=14,
    titleFontSize=14
).add_params(search_box)

chart
```

![image](https://github.com/vega/altair/assets/63077097/c623d353-37da-4f00-b5c8-4ba7a458816d)

**Comment by joelostblom** [comment]
Great progress @dsmedia !

> Address the hover behavior issue to ensure that only visible points respond to hover events.

Would it be enough to move `.add_params(hover)` to the visible points instead of the hover lines?

> Modify the color encoding to use regions instead of countries, while maintaining the ability to highlight individual country trajectories.

Would it help to set color to 'region' and then use the `detail` encoding for the country?

Feel free to open a PR and we can keep iterating there.

**Comment by dsmedia** [comment]
I've created a pull request [#3459](https://github.com/vega/altair/pull/3459) to address this issue, incorporating suggestions from @joelostblom for addressing problem with hover action over invisible points and encoding colors to regions.

As a side note, while testing the search box (proving its value!) I discovered a discrepancy between the official Gapminder datasets on [life expectancy](https://www.gapminder.org/data/documentation/gd004/
) and [fertility](https://www.gapminder.org/data/documentation/gd008/
), and the [vega/vega-datasets](https://github.com/vega/vega-datasets) version of [gapminder.json](https://github.com/vega/vega-datasets/blob/main/data/gapminder.json). The North and South Korea labels appear to be reversed in the vega-datasets version, showing e.g. that North Korea has a higher life expectancy in 2005 than South Korea. which may need further investigation. Should I create an issue on that repo?

**Comment by joelostblom** [comment]
@dsmedia Great find! Yes please open a PR on the vega-dataset repo swapping the labels of North and South Korea. I will add some comments to #3459 in a few minutes as well

**Comment by dsmedia** [comment]
@joelostblom Data quality/sourcing [issue](https://github.com/vega/vega-datasets/issues/577) raised in vega-datasets.

**Comment by dsmedia** [comment]
I believe this issue can now be closed. @joelostblom or another maintainer, could you please review and close this if you agree?

Also, at what point would the new example get pushed to [the github.io docs page](https://altair-viz.github.io/gallery/index.html)?

**Comment by joelostblom** [comment]
Thank you @dsmedia ! We usually build the docs as part of creating a new release, since there could be new functionality that we don't want to publish until the corresponding version of altair is out.
