### ISSUE TITLE
Potentially simplify _check_if_valid_subspec and _check_if_can_be_layered

### ISSUE THREAD

**Issue by binste** [vega/altair#3518]
### What is your suggestion?

See https://github.com/vega/altair/pull/3508#issuecomment-2264835491. CC @dangotbanned

**Comment by dangotbanned** [comment]
Thanks for the ping @binste 

More detail in the linked comment, but this would be looking at removing some `dict`-related code (+ maybe annotations?) for compound charts.

Constructing charts in that way appears to always error, since only the earlier parts assume a `dict` may have been provided by the user.

IIRC there wasn't test coverage for those scenarios, nor was it demonstrated in examples
