### ISSUE TITLE
ImportError: cannot import name 'TypeIs' from 'typing_extensions' (c:\Users\...\site-packages\typing_extensions.py)

### ISSUE THREAD

**Issue by ProgramerSalar** [vega/altair#3615]
### What happened?

![Screenshot 2024-09-27 185549](https://github.com/user-attachments/assets/9166bfee-deac-4849-bbf1-a93ea8fa8b9c)

**Comment by dangotbanned** [comment]
Although no info was provided on the `altair` version used, this is due to requiring https://github.com/python/typing_extensions/releases/tag/4.10.0

Closing as this is specified in our dependencies

https://github.com/vega/altair/blob/6beec7bf0819d961d3d32823d7e658429c306b97/pyproject.toml#L16-L18


@ProgramerSalar if you've not fixed this already, be sure to update your version of `altair`
