### ISSUE TITLE
JupyterChart dark theme with vegafusion datatransformer

### ISSUE THREAD

**Issue by Jhsmit** [vega/altair#3677]
### What happened?

I'm trying to make a JupyterChart in dark theme with the vegafusion transformed enabled. 
code:

```python
df = pl.DataFrame({"x": [1, 2, 3], "y": [4, 5, 6]})
chart = alt.Chart(df).mark_point().encode(x="x",y="y")
```

with default transformer:
![Image](https://github.com/user-attachments/assets/03b54291-ce86-4547-b00f-7f3346c2c390)

with vegafusion:
![Image](https://github.com/user-attachments/assets/731eac86-f7ac-4a49-8981-2d01130f0310)

When I click "Open in Vega Editor" I see the same behavior, so my reasoning was therefore the vega-lite spec generated has a bug and the issue should be reported here. 

### What would you like to happen instead?

Expected behavior is the graph to look the same as with the default transformer

### Which version of Altair are you using?

5.4.1

**Comment by jonmmease** [comment]
Hi @Jhsmit, could you try applying the theme with `alt.themes.enable` following [Changing the Theme](https://altair-viz.github.io/user_guide/customization.html#changing-the-theme) docs?

What's happening is that the VegaFusion data transformer converts the Vega-Lite spec to Vega using vl-convert in Python (because VegaFusion operates on Vega specifications) and this Vega specification is what is sent to the browser for display. But Vega-Embed themes (supplied to `embed_options`) are applied only in the browser at display time, and they only apply to Vega-Lite charts (not Vega). By using `alt.themes.enable`, the theme gets applied in Python before the conversion to Vega.

All that said, I think it would make sense for us to look for a theme in `embed_options` when VegaFusion is enabled and do this automatically.

**Comment by Jhsmit** [comment]
That works! thanks

```python
alt.themes.enable('dark')
alt.data_transformers.enable("vegafusion")
alt.JupyterChart(chart, embed_options={'theme': 'dark'})
```

![Image](https://github.com/user-attachments/assets/9d1149a0-a41c-4432-9c01-44ee959aed1c)
